apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-miniprojet-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-miniprojet
  template:
    metadata:
      labels:
        app: k8s-miniprojet
    spec:
      containers:
        - name: k8s-miniprojet
          image: blooomoo/k8s-microproject
          ports:
            - containerPort: 3000